### ISSUE TITLE
Controlling real hardware

### ISSUE THREAD

**Issue by gokul-gokz** [ROBOTIS-GIT/open_manipulator#11]
I have a 6 DOF manipulator made of dynamixel MX servos. I have modified the open manipulator code such that it can read the current states of the actuators and can visualize the manipulator current configuration in the RVIZ. I have also configured the arm with moveit.I can execute fake joint trajectory execution in moveit.  
Then I also configured open manipulator position control code by changing the number of joints and also updated the joint names. 
Generally moveit searches for controllers in controllers.yaml file . Then it sends the trajectory through action client interface which is configured in that.  But in the open manipulator code, trajectory execution is through the position_controller node.  Then whenever I try to plan and execute in moveit, the node crashes throwing the error

> [ERROR] [1505907451.220483043]: Unable to identify any set of controllers that can actuate the specified joints: [ joint1 joint2 joint3 joint4 joint5 joint6 ]
[ERROR] [1505907451.220602981]: Known controllers and their joints:
[ERROR] [1505907451.220710063]: Apparently trajectory initialization failed
[ INFO] [1505907451.227786522]: ABORTED: Solution found but controller failed during execution
position_controller: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:413: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.

How to solve this issue?

**Comment by ROBOTIS-Will** [comment]
Hello gokul-gokz,
Please read [this thread](https://answers.ros.org/question/250855/no-known-controllers-and-their-joints-in-moveit-when-connecting-real-robot/) and see if it helps to solve your problem.

**Comment by routiful** [comment]
Hi @gokul-gokz , sorry for late reply

SRDF is configured by setup assistant based on URDF.
After changing an URDF for your robot, you have to modified open_manipulator_position_ctrl package and open_manipulator_dynamixel_ctrl package.
These packages include move_node and dynamixel_workbench. You need to check define the number of dynamixels and joints.
This number is related with error message of Eigen lib.

Thanks
Darby
