### ISSUE TITLE
Use U2D2 to controll OM failed

### ISSUE THREAD

**Issue by zhl017** [ROBOTIS-GIT/open_manipulator#111]
As title
My environment is PC(Ubuntu16.04 + kinetic) + U2D2 + SMPS2DXL + OM
What I already do :
1. set servos ID 11 to 15 and baudrate set 1000000mbps.
2. USB Latency Timer Setting finish

When I run `roslaunch open_manipulator_controller open_manipulator_controller.launch` 
Show this error 
![123](https://user-images.githubusercontent.com/33046512/62861683-d58a3900-bd36-11e9-9183-5a07d72d67bb.jpg)

But when I use old USBtoDynamixel, it can success work

**Comment by gpwhd07** [comment]
hi @zhl017 
Thanks for using OM.
We need more information about your situation.
I think that problem may be due to U2D2.

Please check again that dynamixel successfully work in your hardware environments, by using the dynamixel wizard 2.0. 
http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_wizard2/

**Comment by zhl017** [comment]
yes, it can work at wizard 2.0.
I use two U2D2, both happened this problem.
by the way, I use XM430-W350-R instead XM430-W350-T

**Comment by rjshim** [comment]
@zhl017 

Would you test if [this](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_workbench/#controllers) work ? 

Regards,
Ryan

**Comment by zhl017** [comment]
good to work ...
![123](https://user-images.githubusercontent.com/33046512/62916350-a02f2b00-bdca-11e9-86e4-3ee7de549ac3.jpg)

**Comment by rjshim** [comment]
@zhl017 

Please test the next one (5.1.2) to see if the motor controller works properly.
You need to set your motor ids to 1,2 (you need two motors for this example)

Regard,
Ryan

**Comment by zhl017** [comment]
Can't work and I didn't see `/dynamixel_command`..
I clone wrong package ??
![1565674349732](https://user-images.githubusercontent.com/33046512/62917538-35ccb980-bdcf-11e9-85b0-d3424a9d44da.jpg)
![1565674484600](https://user-images.githubusercontent.com/33046512/62917542-3a916d80-bdcf-11e9-8045-57c1494244ea.jpg)

**Comment by rjshim** [comment]
@zhl017 

Please do the followings
1. Update your motor firmware with DXL-Wizard
2. Download the latest version of WB package

and let me know if it still doesn't work.

Regards,
Ryan

**Comment by zhl017** [comment]
![1565674484600](https://user-images.githubusercontent.com/33046512/62919563-a8409800-bdd5-11e9-9c4c-38a5c2f4a4af.jpg)

**Comment by zhl017** [comment]
I use `git clone https://github.com/ROBOTIS-GIT/dynamixel-workbench.git` yesterday
I think it's the latest version.
and my motor firmware also the latest
![1565677143953](https://user-images.githubusercontent.com/33046512/62919583-b8587780-bdd5-11e9-9204-215f4ca458ea.jpg)

**Comment by rjshim** [comment]
@zhl017 

Would you test if [this tutorial](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/sample_code/cpp_sync_read_write_protocol_2_0/#cpp-sync-read-write-protocol-20) works?

Regards,
Ryan

**Comment by zhl017** [comment]
sorry for reply late.
I try sync_read_write C++ example
Motor can move one times and then show failed.
![1565750936347](https://user-images.githubusercontent.com/33046512/62991226-55bcb580-be81-11e9-80ea-7c67bf84893f.jpg)

**Comment by rjshim** [comment]
@zhl017 

1. Would you connect your U2D2 to a USB hub and connect to it to your computer, and test it again? 
2. Check if you really changed USB latency](http://emanual.robotis.com/docs/en/platform/openmanipulator_x/ros_setup/#usb-latency-timer-setting) and test it again.
3. If it still doesn't work, the problem might be on your U2D2, so just buy a new one.

Regards,
Ryan

**Comment by zhl017** [comment]
So strange, I change another PC, it can work now !!

thanks.
