### ISSUE TITLE
OpenManipulator with OpenCR but without Serial-USB

### ISSUE THREAD

**Issue by morusa** [ROBOTIS-GIT/open_manipulator#123]
Hi,

I try to manipulate the OpenManipulator without the use of a computer.

I want to control it using an RC-100, or with the SW1 and SW2 buttons on the OpenCR card.

I based on the example: open_manipulator_chain on Arduino IDE for OpenCR, everything works perfect.

But it doesn't work if the usb cable is not connected to the computer. That is, if I disconnect the computer and restart the OpenCR no longer works, that connection is waiting ... it seems that Dynamixel SDK waits for a serial port to always be connected.

How can I make it work as an embedded system?

Regards

**Comment by gpwhd07** [comment]
Hi @morusa 

Please check that following code is disabled of `void setup()` function in `open_manipulator_chain.ino`

> // while (!Serial)
> // ;

If it is disabled, disable the following codes further in `open_manipulator_chain.ino`.

> Serial.begin(57600);

and

> connectProcessing(platform_state);

and 

>   if (availableProcessing())
>   {
>     get_processing_data = readProcessingData();
>     processing_state = true;
>   }

If you do this, the firmware will no longer be connected to the PC via the USB port.

Thanks.
