### ISSUE TITLE
ROS2 Simulation

### ISSUE THREAD

**Issue by Le0nLyn** [ROBOTIS-GIT/open_manipulator#128]
Hi Robotis,
Right now, I am exploring the [gym-gazebo](https://github.com/AcutronicRobotics/gym-gazebo2) repo to do some reinforcement learning research with open-manipulator-x and gym, but the gym-gazebo repo uses ROS2. I'm wondering when will simulation for open-manipulator-x be supported on ROS2 or are there any pointers for me to build it on my own?

**Comment by rjshim** [comment]
@Le0nLyn 

Currently, we have no concrete plans for further ROS2 development for OpenManipulator. The reason simulation wasn't released together with other packages was that the plugin for position controlling joints hadn't been ported at the time. I guess you might need to wait until early next year.

Regards,
Ryan

**Comment by Le0nLyn** [comment]
Thank you! I'll check on this earlier next year.

**Comment by rfzeg** [comment]
Hello Robotis,
any update on the Gazebo simulation of OpenManipulator running ROS2 natively?

Where can I check if the plugin for position controlling joints has been ported to ROS2 ?

Regards,

Roberto
