### ISSUE TITLE
Questions about open_manipulator on turtlebot3

### ISSUE THREAD

**Issue by hozhu** [ROBOTIS-GIT/open_manipulator#13]
Dear Robotis Representative,

My team recently purchased a turtlebot3 from Robotis and the package came with a intel joule 570x board and OpenCR 1.0 board. In addition to that, we have reproduced and assembled an open-manipulator using five Dynamixel X-series servos. Now, we are trying to control the open-manipulator using the OpenCR 1.0 board and we are having some difficulties. **First,** we are not sure if we need to upload new Arduino code into the OpenCR 1.0 board in order to control the open-manipulator. **Second**, we have set the dynamixel servos to position control mode, 1000000 baudrate and ID numbers of 3,4,5,6,7 (one ID number for each of the five dynamixel servos), and we are not sure if we are setting these parameters correctly. **Lastly**, would there be a more detailed guideline on how to control the open-manipulator? We have followed this website : http://turtlebot3.readthedocs.io/en/latest/manipulation.html and it did not work very well. Thank you for your help and time in advance!

SIncerely,

Hong

**Comment by ROBOTIS-Will** [comment]
Hello Hong,

Thank you for your inquiry.  
The Arduino code is currently uploaded from [Github](https://github.com/ROBOTIS-GIT/open_manipulator/tree/master/Arduino/OpenManipulator/OPM_for_Arduino/Chain/open_manipulator_chain).  
However, the code depending on other packages such as Dynamixel SDK and Dynamixel Workbench, setting the environment might be complicated.  
Official OpenManipulator code will be available when the product is released to the market.  
Thank you.
