### ISSUE TITLE
Is there a dynamic model program here

### ISSUE THREAD

**Issue by Sunchanghao** [ROBOTIS-GIT/open_manipulator#133]
Hello
I want to modify the size of open_manipulator_x 
so is there a dynamic model program here that I can modify the parameter?
THX

**Comment by rjshim** [comment]
What do you mean dynamic model program? You want to change the size of robot links?

Ryan

**Comment by Sunchanghao** [comment]
hello
The manipulator is mounted on the drone

so I need to calculate the center of gravity changes
thus I need to model the motion of the manipulator～






At 2019-11-19 10:56:53, "Ryan Jaehyun Shim" <notifications@github.com> wrote:


What do you mean dynamic model program? You want to change the size of robot links?

Ryan

**Comment by rjshim** [comment]
@Sunchanghao 

Please rerfer to [this](https://github.com/ROBOTIS-GIT/open_manipulator/blob/master/open_manipulator_description/urdf/open_manipulator.urdf.xacro)

Regards,
Ryan

**Comment by Sunchanghao** [comment]
@rjshim Thanks
I have a question,is the calculation of the Denavit-Hartenberg(D-H) of the manipulator done in Movelt!?
