### ISSUE TITLE
Problem with Current-based Position Control mode

### ISSUE THREAD

**Issue by morusa** [ROBOTIS-GIT/open_manipulator#135]
Hi

I am use the robot in <code>Current-based Position Control mode</code> works well, I was able to limit the torque to the required parameters.

But there is a problem of "tremors."  Please watch the following video.

https://youtu.be/DCceEq14ttU

These tremors according to my analysis are due to the "backlash" of the servomotor gear.

please, with all the experience you have, what parameters could you adjust to eliminate this trembling behavior?

If I return the robot to <code>position_mode</code> the behavior is perfect, but how can I monitor the current that each servomotor is demanding? In order to protect the servomotors when the user tries to move the arm in a direction where an obstacle is found.

**Comment by rjshim** [comment]
@morusa 

You can change the position PID gains for your motors with Dynamixel Wizard. If the d gain is set to 0, increase it to reduce the tremors. Test it and let us know the result. 

Regards,
Ryan

**Comment by rjshim** [comment]
As there have been no updates, I will close this issue.

Ryan
