### ISSUE TITLE
Kinematics Pose in Simulation isn't always right

### ISSUE THREAD

**Issue by KiraScience** [ROBOTIS-GIT/open_manipulator#136]
Hello
I am currently working with the simulation only of the Open Manipulator-X. Now I detected a possible Problem with the kinematics that is problematic for my task.
If parts of the manipulator touched the ground, you wont see a movement after that, But in task space the values can change for a while after that.
For example if the gripper point touches the ground slightly, the z-value in task space should be around 0. Now you can type in a higher value in joint space to touch the ground "harder". In the simulation you don't see a reaction obviously but the z-value in task space changes to a number <0, which should not be possible because of the ground plane. If you want to move the gripper up again in very small steps, it takes a while until you see the manipulator move again because of the wrong kinematics position.
![TouchTheGroundSlightly](https://user-images.githubusercontent.com/58778000/70628435-70811a00-1c28-11ea-842f-d79834b3d394.png)
![AfterChangingjoint2again](https://user-images.githubusercontent.com/58778000/70628444-7676fb00-1c28-11ea-8836-283f18f2cfed.png)
Do you have an idea how to fix that problem? 
I've implemented a node, so that I can control the manipulator with two joysticks. Now i want to do a kind of fitt's task exercise so you have to touch rectangles on the ground. Then the time needed for the path between two rectangles is measured, but the manipulator looks like not reacting for a while after touching the ground because of the negative z-value in task space. Sadly this distorts my Results.
Thank you in advance

Edit: It seems that the open Manipulator has no collision detection. Is that right?

**Comment by rjshim** [comment]
@KiraScience 

You have to click on the 'Read kinematic pose' button to read the current position in the Cartesian space. Let us know if you have any other questions.

Regards,
Ryan
