### ISSUE TITLE
Thingiverse missing right RAIL_BLOCK stl

### ISSUE THREAD

**Issue by nxdefiant** [ROBOTIS-GIT/open_manipulator#137]
Hi,

it seems to me that the Open Manipulator [package on Thingiverse](https://www.thingiverse.com/thing:3069574) is missing the stl file for the right rail block? It has the "RAIL_BLOCK.stl" which I believe is the left one.

**Comment by rjshim** [comment]
@nxdefiant  

You can just print out two of that file. It should be up down symmetric.

Ryan.

**Comment by nxdefiant** [comment]
it doesn't look very symmetric to me..

Also flipping one axis is not an option because of the nose on the edge.

**Comment by rjshim** [comment]
@nxdefiant 

Maybe the part you say is not the RAIL_BLOCK.stl file but something else. Check the [part list](http://emanual.robotis.com/docs/en/platform/openmanipulator_x/assembly/). 

Ryan

**Comment by nxdefiant** [comment]
sorry my fault. Its the RAIL_BRACKET was referring to.

**Comment by nxdefiant** [comment]
This:
![image](https://user-images.githubusercontent.com/885742/70971546-87e55a80-20a1-11ea-9e80-9fe0cda66b55.png)

**Comment by rjshim** [comment]
@nxdefiant 

Thank you for the report. I just updated the uploadings. Download them and let us know if you still have other issues.  :)

Ryan

**Comment by nxdefiant** [comment]
That looks good, thanks.
