### ISSUE TITLE
Can I control robot joint velocities?

### ISSUE THREAD

**Issue by zongyaojin** [ROBOTIS-GIT/open_manipulator#139]
Hello,

I'm wondering if this package allows me to control the velocity of individual joints? For example, I would like to command joint [1,2,3,4,5,6] to rotate at [7,3,12,9,15,20] degrees per second. Is this possible? If so, which ROS Topic should I use?

**Comment by rjshim** [comment]
@zongyaojin 

You will have to build your own package using [DynamixelSDK](http://emanual.robotis.com/docs/en/software/dynamixel/dynamixel_sdk/overview/).

Ryan
