### ISSUE TITLE
open_manipulator class not found

### ISSUE THREAD

**Issue by hozhu** [ROBOTIS-GIT/open_manipulator#14]
https://github.com/ROBOTIS-GIT/open_manipulator/blob/326171271aa1d42bfddbbe73d81c48435623deae/Arduino/OpenManipulator/OPM_for_Arduino/Chain/open_manipulator_chain/open_manipulator_chain_config.h#L95

The class 'open_manipulator' cannot be found. Can you share the file or where I can find the definition? Thanks.

**Comment by routiful** [comment]
Hi :) @hozhu 

You need to copy src, include folders and library.properties file and paste it into Arduino library.
Then you can solve that problem.

Thanks
Darby
