### ISSUE TITLE
I have question about open manipulator current comsumption . 

### ISSUE THREAD

**Issue by hyunoklee** [ROBOTIS-GIT/open_manipulator#145]
Hello. :)
 I am trying to run an open manipulator using a battery and a U2D2 and PowerHub.
At Open manipulator emanual, I can see that 12V voltage is applied to PowerHub. But I can find current comsumption at 12V. 
The informaition is needed to calculate the battery life time . Can you tell me how much current is being consumed by open manipulator at 12V?
thank you.

**Comment by rjshim** [comment]
@hyunoklee 

Please refer to the [link](http://emanual.robotis.com/docs/en/dxl/x/xm430-w350/). 

Ryan

**Comment by hyunoklee** [comment]
thank you~
