### ISSUE TITLE
Operating the Dynamixel-XM430 motors in Current Control Mode.

### ISSUE THREAD

**Issue by snehalstomar** [ROBOTIS-GIT/open_manipulator#148]
Hi! I have the following questions:

1. What is the procedure to operate all the motors of the OpenManipulator-X in current control(torque) mode while getting current feedback?
2. Are there any existing simulations available wherein, the motors are operating in current control mode?

**Comment by rjshim** [comment]
@snehalstomar 

OpenMANIPULATOR does not support torque-based control yet. If you are fine with testing your controller in the simulation environment, [this repository](https://github.com/modulabs/arm-control) might be a good option.

Ryan
