### ISSUE TITLE
In case of emergency, what is the best and fastest way to shut down the manipulator?

### ISSUE THREAD

**Issue by robotiscustomer** [ROBOTIS-GIT/open_manipulator#151]
Hi, in case the motors do not move as expected and part of the arm starts hitting itself or something else, what is the best and fastest way to shut down the manipulator? If I just unplug the SMPC, will I damage the motors or corrupt the software system? After that, what is the best way to restart the system?

**Comment by rjshim** [comment]
Hi @robotiscustomer 

As it is a more actuator-related question, please leave it at the [link](http://en.robotis.com/service/forum.php) 

Ryan
