### ISSUE TITLE
Broken link in emanual for Open Manipulator-X

### ISSUE THREAD

**Issue by robotiscustomer** [ROBOTIS-GIT/open_manipulator#156]
Hi, under Section 5.4.2 OpenCR, it states that "if you want to operate OpenMANIPULATOR-X on embedded system (OpenCR) without ROS, please refer OpenCR Setup."

The OpenCR Setup link is broken.

Please fix it.

**Comment by ROBOTIS-David** [comment]
Thank you for your report, the broken link will be updated from the next e-Manual update.

**Comment by robotiscustomer** [comment]
Thanks David. In regard to the e-Manual, what is the best way to print it? If I just print as is, sometimes 1/3-1/2 of the pages are for Table of Contents. Some codes/commands are cut off and not being printed. If I hit Edit on GiHub and print, all the section numbers are missing. Also, how can I tell which version of the e-Manual I am reading and the version of the manual posted on the website?

**Comment by ROBOTIS-David** [comment]
Hi, Thanks for your reply, 

- If you are using Chrome, just save as **_webpage,complete_**, which preserves most contents on the page, and then print the page. 
- Unfortunately, the current e-Manual does not provide the version information as the manual is often upadated for new features. 

I hope this information is helpful for you .

Many thanks, 

David Park.

**Comment by robotiscustomer** [comment]
Thanks David. Please keep safe and healthy.

**Comment by ROBOTIS-David** [comment]
No worries, If you have any further questions requiring assistance, please feel free to reach out to us at any time. But if not, please close this thread.

**Comment by robotiscustomer** [comment]
Thanks. It could be helpful if the date of the last updated information is included.
