### ISSUE TITLE
Error 1 Invoking "make cmake_check_build_system" failed

### ISSUE THREAD

**Issue by robotiscustomer** [ROBOTIS-GIT/open_manipulator#159]
Hi, I have followed the steps to install ROS1 under Ubuntu 16.04 manually. Then, I installed some libraries for OpenManipulator-X using the steps described in the e-Manual. When I executed catkin_make in the last step, the titled error showed up. Can you tell me how to fix this please? Thanks

Here is the commands I used:

1  cd Downloads/
2  ls
3  chmod +x NVIDIA-Linux-x86_64-440.82.run 
4  sudo ./NVIDIA-Linux-x86_64-440.82.run  --no-x-check
5  sudo reboot
6  sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
7  sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
8  sudo apt-get update
9  sudo apt-get install ros-kinetic-desktop-full
10 sudo apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential 
11 sudo sudo apt install python-rosdep 
12 sudo rosdep init 
13 rosdep update 
14 echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc 
15 source ~/.bashrc 
16 env | grep ROS 
17 vi .bashrc 
18 mkdir -p ~/catkin_ws/src 
19 cd ~/catkin_ws/ 
20 catkin_make 
21 cd devel 
22 ls 
23 cd .. 
24 source devel/setup.bash 
25 echo $ROS_PACKAGE_PATH 
26 /home/youruser/catkin_ws/src:/opt/ros/kinetic/share 
27 echo $ROS_PACKAGE_PATH /home/youruser/catkin_ws/src:/opt/ros/kinetic/share 
28 cd ~ 
29 sudo apt-get install ros-kinetic-ros-controllers ros-kinetic-gazebo* ros-kinetic-moveit* ros-kinetic-industrial-core 
30 cd ~/catkin_ws/src/ 
31 git clone https://github.com/ROBOTIS-GIT/Dynami... 
32 git clone https://github.com/ROBOTIS-GIT/dynami... 
33 git clone https://github.com/ROBOTIS-GIT/dynami... 
34 git clone https://github.com/ROBOTIS-GIT/open_m... 
35 git clone https://github.com/ROBOTIS-GIT/open_m... 
36 git clone https://github.com/ROBOTIS-GIT/open_m... 
37 git clone https://github.com/ROBOTIS-GIT/roboti... 
38 cd ~/catkin_ws && catkin_make

user@ubuntu:~/catkin_ws$ catkin_make Base path: /home/user/catkin_ws Source space: /home/user/catkin_ws/src Build space: /home/user/catkin_ws/build Devel space: /home/user/catkin_ws/devel Install space: /home/user/catkin_ws/install

#
Running command: "make cmake_check_build_system" in "/home/user/catkin_ws/build"
#
-- Using CATKIN_DEVEL_PREFIX: /home/user/catkin_ws/devel -- Using CMAKE_PREFIX_PATH: /home/user/catkin_ws/devel;/opt/ros/kinetic -- This workspace overlays: /home/user/catkin_ws/devel;/opt/ros/kinetic -- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") -- Using PYTHON_EXECUTABLE: /usr/bin/python2 -- Using Debian Python package layout -- Using empy: /usr/bin/empy -- Using CATKIN_ENABLE_TESTING: ON -- Call enable_testing() -- Using CATKIN_TEST_RESULTS_DIR: /home/user/catkin_ws/build/test_results -- Found gtest sources under '/usr/src/gmock': gtests will be built -- Found gmock sources under '/usr/src/gmock': gmock will be built -- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") -- Using Python nosetests: /usr/bin/nosetests-2.7 -- catkin 0.7.20 -- BUILD_SHARED_LIBS is on -- BUILD_SHARED_LIBS is on -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -- ~~ traversing 16 packages in topological order: -- ~~ - dynamixel_workbench (metapackage) -- ~~ - open_manipulator (metapackage) -- ~~ - open_manipulator_simulations (metapackage) -- ~~ - dynamixel_workbench_msgs -- ~~ - open_manipulator_msgs -- ~~ - dynamixel_sdk -- ~~ - dynamixel_workbench_toolbox -- ~~ - robotis_manipulator -- ~~ - open_manipulator_libs -- ~~ - dynamixel_workbench_controllers -- ~~ - dynamixel_workbench_operators -- ~~ - open_manipulator_control_gui -- ~~ - open_manipulator_controller -- ~~ - open_manipulator_teleop -- ~~ - open_manipulator_description -- ~~ - open_manipulator_gazebo -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -- +++ processing catkin metapackage: 'dynamixel_workbench' -- ==> add_subdirectory(dynamixel-workbench/dynamixel_workbench) -- +++ processing catkin metapackage: 'open_manipulator' -- ==> add_subdirectory(open_manipulator/open_manipulator) -- +++ processing catkin metapackage: 'open_manipulator_simulations' -- ==> add_subdirectory(open_manipulator_simulations/open_manipulator_simulations) -- +++ processing catkin package: 'dynamixel_workbench_msgs' -- ==> add_subdirectory(dynamixel-workbench-msgs/dynamixel_workbench_msgs) -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy -- dynamixel_workbench_msgs: 18 messages, 2 services -- +++ processing catkin package: 'open_manipulator_msgs' -- ==> add_subdirectory(open_manipulator_msgs) -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy -- open_manipulator_msgs: 3 messages, 6 services -- +++ processing catkin package: 'dynamixel_sdk' -- ==> add_subdirectory(DynamixelSDK/ros) -- +++ processing catkin package: 'dynamixel_workbench_toolbox' -- ==> add_subdirectory(dynamixel-workbench/dynamixel_workbench_toolbox) -- +++ processing catkin package: 'robotis_manipulator' -- ==> add_subdirectory(robotis_manipulator) -- +++ processing catkin package: 'open_manipulator_libs' -- ==> add_subdirectory(open_manipulator/open_manipulator_libs) -- +++ processing catkin package: 'dynamixel_workbench_controllers' -- ==> add_subdirectory(dynamixel-workbench/dynamixel_workbench_controllers) -- +++ processing catkin package: 'dynamixel_workbench_operators' -- ==> add_subdirectory(dynamixel-workbench/dynamixel_workbench_operators) -- +++ processing catkin package: 'open_manipulator_control_gui' -- ==> add_subdirectory(open_manipulator/open_manipulator_control_gui) CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfig.cmake:27 (message): The imported target "Qt5::Gui" references the file

 "/usr/lib/x86_64-linux-gnu/libEGL.so"
but this file does not exist. Possible reasons include:

The file was deleted, renamed, or moved to another location.
An install or uninstall procedure did not complete successfully.
The installation package was faulty and contained

"/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

but not all the files it references.
Call Stack (most recent call first): /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:50 (_qt5_Gui_check_file_exists) /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:72 (_qt5gui_find_extra_libs) /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfig.cmake:158 (include) /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:99 (find_package) open_manipulator/open_manipulator_control_gui/CMakeLists.txt:21 (find_package)

-- Configuring incomplete, errors occurred! See also "/home/user/catkin_ws/build/CMakeFiles/CMakeOutput.log". See also "/home/user/catkin_ws/build/CMakeFiles/CMakeError.log". Makefile:318: recipe for target 'cmake_check_build_system' failed make: * [cmake_check_build_system] Error 1 Invoking "make cmake_check_build_system" failed

**Comment by robotiscustomer** [comment]
Sorry not sure why some lines got crossed out by Github.

**Comment by ROBOTIS-Will** [comment]
@robotiscustomer 
Looks like you're missing some libraries or those are not properly installed.
Please refer to below to see if this is a similar case with yours.
https://www.reddit.com/r/Ubuntu/comments/g1sh09/the_imported_target_qt5gui_references_the_file/

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't any recent activity. Please feel free to reopen when necessary.

**Comment by LOKAKSHAI** [comment]
When I'm trying to build the system it show the error

Invoking "make cmake_check_build_system" failed

**Comment by ROBOTIS-Will** [comment]
@LOKAKSHAI 
Which Ubuntu and ROS do you use?
Could you copy and paste your terminal output?

**Comment by LOKAKSHAI** [comment]
Hi team,

Thanks for your reply.

I'm using
 ubuntu 18.04
 Ros 1

Kindly check and let me know about your feedback.

**Comment by ROBOTIS-Will** [comment]
@LOKAKSHAI 
Have you run the `catkin_make` command under the `catkin_ws` directory?
Since this is not the issue of open manipulator, please refer to ROS Answers for more information.
There are many questions with the same error message.
https://answers.ros.org/questions/query:Invoking%20%22make%20cmake_check_build_system%22%20failed/
Thanks
