### ISSUE TITLE
issues in catkin_make

### ISSUE THREAD

**Issue by albinbiju** [ROBOTIS-GIT/open_manipulator#173]
in order to catkin_make u need to clone the following repositories too:

https://github.com/ROBOTIS-GIT/open_manipulator_msgs.git
https://github.com/ROBOTIS-GIT/open_manipulator_simulations.git
https://github.com/ROBOTIS-GIT/robotis_manipulator.git

**Comment by ROBOTIS-Will** [comment]
@albinbiju 
open_manipulator package has dependencies in several other packages.
Please refer to below eManual section for necessary packages.
http://emanual.robotis.com/docs/en/platform/openmanipulator_x/ros_setup/#install-ros-packages

**Comment by albinbiju** [comment]
But I still don't get the joints topic published in the latest versions of the open manipulator

**Comment by ROBOTIS-Will** [comment]
@albinbiju 
In the recent update, there was a change in major controller interface and now it is designed to use moveit. You can get each joint value from the position in /joint_states topic.
![image](https://user-images.githubusercontent.com/26239359/81788955-47014d00-953e-11ea-9185-6d101df18022.png)

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't any recent activity. Please feel free to reopen when necessary.
