### ISSUE TITLE
Can't control Gripper in chain_teaching on Arduino

### ISSUE THREAD

**Issue by Wolfman038** [ROBOTIS-GIT/open_manipulator#182]
Hi I'm having an issue where in the chain_teaching example on Arduino.  When I save a pose in the serial monitor, it registers that the gripper servo is moving, however when i run the movements, the gripper does not move at all. I know the gripper servo still works, because when the movements start, the motor returns to 0 position so idk why the servo wont move.

**Comment by ROBOTIS-Will** [comment]
Hi,
There are min/max limits for the gripper setting. If the gripper value is greater than 0.010 or smaller than -0.010, gripper will not operate.
Also, please make sure that you have correct orientation for the gripper assembly especially aligning the horn marking.
![image](https://user-images.githubusercontent.com/26239359/89745141-b4e0f480-daec-11ea-91b4-7b6959a26114.png)

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't any recent activity. Please feel free to reopen when necessary.
