### ISSUE TITLE
where can I find the file of open_manipulator.urdf.Thanks

### ISSUE THREAD

**Issue by sunyuechang** [ROBOTIS-GIT/open_manipulator#184]

**Comment by ROBOTIS-Will** [comment]
You can find it in the below location of this repository.
Note that we provide xacro file instead.
Thank you.
https://github.com/ROBOTIS-GIT/open_manipulator/blob/master/open_manipulator_description/urdf/open_manipulator.urdf.xacro

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't any recent activity. Please feel free to reopen when necessary.
