### ISSUE TITLE
OpenCr Modbus RTU

### ISSUE THREAD

**Issue by LuchianRazvanAdrian** [ROBOTIS-GIT/open_manipulator#185]
Is it a posibility to use Modbus RTU on OpenCR? I see it has 3 ports with RS485. Can you provide me the required code?

**Comment by ROBOTIS-Will** [comment]
Hi @LuchianRazvanAdrian 
Yes, OpenCR can support the Modbus RTU based RS485, but the protocol library is not provided.
Thank you.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't any recent activity. Please feel free to reopen when necessary.
