### ISSUE TITLE
Moveit : Failed to rotate in yaw direction!

### ISSUE THREAD

**Issue by ZhengQiushi** [ROBOTIS-GIT/open_manipulator#193]
hi, I met problem when running moveit with open manipulator in rviz. It seems that the arm can not rotate in the yaw direction, which means it can't rotate from left to right? I wonder how can I solve this problem?

**Comment by ROBOTIS-Will** [comment]
Hi @ZhengQiushi 
Sorry about the delayed response.
MoveIt in RViz is designed for 6 DOF manipulator, and solving 4DOF OpenMANIPULATOR-X can be limited by MoveIt.
For more flexibility, you may want to use the [GUI program](https://emanual.robotis.com/docs/en/platform/openmanipulator_x/ros_operation/#gui-program).

**Comment by yun-goon** [comment]
This issue will be closed due to prolonged inactivity. Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
