### ISSUE TITLE
Issue Installing ROS for Dashing (Ubuntu 18.04) 

### ISSUE THREAD

**Issue by darvizu061** [ROBOTIS-GIT/open_manipulator#194]
I'm following the [manual](https://emanual.robotis.com/docs/en/platform/openmanipulator_x/quick_start_guide/#quick-start-guide) to install ROS for Dashing. When I run the command `chmod 755 ./install_ros_dashing.sh` I get the error "No such file or directory. This is because the prior command `wget https://raw.githubusercontent.com/ROBOTIS-GIT/robotis_tools/master/install_ros2_dashing.sh` saves the file name as install_ros2_dashing.sh. To work around this, I run `chmod 755 ./install_ros2_dashing.sh` and it runs without errors. 

However, when I run next command in the manual `bash ./install_ros2_dashing.sh`, I get an error saying "bash: /opt/ros/dashing/setup.bash: No such file or directory". Can someone provide a solution?

**Comment by ROBOTIS-Will** [comment]
Closing this issue as there isn't any recent activity. Please feel free to reopen when necessary.
