### ISSUE TITLE
ros2 branch contains `open_manipulator_x` instead of `open_manipulator`

### ISSUE THREAD

**Issue by goekce** [ROBOTIS-GIT/open_manipulator#195]
I noticed that the packages in `ros2` branch are prefixed with `open_manipulator_x` instead of `open_manipulator`. Maybe the reason is that not all packages are ported to ros2.

Is this naming issue a bug or feature?

**Comment by ROBOTIS-Will** [comment]
Some customers were confused with this package as it could be used for OpenMANIPULATOR-P, and beginning with ROS2, the package has renamed to open_manipulator_x.
However, ROS1 packages were already released with the prefix of "open_manipulator", the package name has been left as is.
Naming is the most difficult task for developers and this seems one of them.
