### ISSUE TITLE
Open Manipulator X Pick and place

### ISSUE THREAD

**Issue by LuchianRazvanAdrian** [ROBOTIS-GIT/open_manipulator#196]
Hello,
There is a pick and place application for open manipulator x? I know there is one, but for master and slave application.

**Comment by ROBOTIS-Will** [comment]
Hi @LuchianRazvanAdrian 
Sorry about the delayed reponse.
There is a pick and place example based on vision.

**Comment by yun-goon** [comment]
This issue appears to be resolved, so it will be closed.
