### ISSUE TITLE
[ERROR] [OpenManipulator Chain Custom]fail to solve inverse kinematics [ERROR] [CUSTOM_TASK_TRAJECTORY] fail to solve IK

### ISSUE THREAD

**Issue by suyunas** [ROBOTIS-GIT/open_manipulator#202]
According to the tutorial while connecting Openmanipulator with OpenCR as follows:
https://emanual.robotis.com/docs/en/platform/openmanipulator_x/quick_start_guide/
I am able to use the teleop and gui appliaction. However on the gui, the manipulator is displaying the following errors while running the 'drawing' tab

[ERROR] [OpenManipulator Chain Custom]fail to solve inverse kinematics
[ERROR] [TASK_TRAJECTORY] Fail to solve IK

is there any thing missing on installation or need to change any file? many thanks
![test](https://user-images.githubusercontent.com/81650263/113854767-274ac700-9797-11eb-99da-e7bc01b2cd57.png)

I am using Ubuntu 16.04 with ROS kinetic

**Comment by ROBOTIS-Will** [comment]
hi @suyunas 
The given pose of X, Y, Z for drawing line is exceeding the operating range and cannot be achieved.
Please try with smaller values first.

**Comment by suyunas** [comment]
solved
