### ISSUE TITLE
Home service challenge ERROR

### ISSUE THREAD

**Issue by suyunas** [ROBOTIS-GIT/open_manipulator#203]
https://emanual.robotis.com/docs/en/platform/turtlebot3/home_service_challenge/

I am using ubuntu 16.04 with ROS1-kinetic and having the following error while following the above link:

roslaunch turtlebot3_home_service_challenge_tools turtlebot3_pi_cam_remote.launch address:=192.168.1.51
... logging to /home/trustai/.ros/log/fa56f3a2-97f7-11eb-a6bc-74da388b010a/roslaunch-trustai-HP-ZBook-Firefly-15-G7-Mobile-Workstation-25397.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.1.49:33827/
remote[192.168.1.51-0] starting roslaunch
remote[192.168.1.51-0]: creating ssh connection to 192.168.1.51:22, user[pi]
/usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
  self._cipher = factory.new(key, *args, **kwargs)
remote[192.168.1.51-0]: failed to launch on tb3:

Authentication to remote computer[pi@192.168.1.51:22] failed.
A common cause of this error is a missing key in your authorized_keys file.

[192.168.1.51-0] killing on exit
unable to start remote roslaunch child: 192.168.1.51-0
The traceback for the exception was written to the log file

-------------------------------------
192.168.1.51 is the ip of tb3 with manipulator and 192.168.1.49 is the ip of RemotePC. Also this example says that both tb3 and RemotePC should be connected under the same ip address which is confusing. Any help??

**Comment by ROBOTIS-Will** [comment]
@suyunas 
It looks like your ssh-key has not been correctly generated.
Please refer to the Remote PC setup and SBC setup section and run the scripts.
https://emanual.robotis.com/docs/en/platform/turtlebot3/home_service_challenge/#remote-pc-setup
