### ISSUE TITLE
Connection to openmanipulator-X through raspberry pi

### ISSUE THREAD

**Issue by suyunas** [ROBOTIS-GIT/open_manipulator#204]
https://emanual.robotis.com/docs/en/platform/openmanipulator_x/ros_controller_package/

![Screenshot from 2021-04-08 13-51-27](https://user-images.githubusercontent.com/81650263/114030443-5bdf8100-9872-11eb-97e3-df6a13eceafb.png)
after running the 2nd command on PC i am having the following errors. Note that when i am using manipulator connected to the PC using a USB cable then it works perfectly but when attached it through raspberry pi 3 on turtlebot3, it gives the error stated below:
![Screenshot from 2021-04-08 13-53-14](https://user-images.githubusercontent.com/81650263/114030724-96491e00-9872-11eb-82db-f7b4914c6bf3.png)

How can i connect to openmanipulator-X through raspberry pi on tb3 and not directly through opencr using usb cable? can somebody list the set of commands for pc and turtlebot3?

**Comment by ROBOTIS-Will** [comment]
Hi, @suyunas 
If you have connected OpenMANIPULATOR-X directly to Raspberry Pi via U2D2, you should change the device port.
Since /dev/ttyACM0 is assigned to OpenCR and /dev/ttyUSB0 is assigned to LDS 1.5, most likely, your U2D2 should have assigned to `/dev/ttyUSB1`.
Please modify the OpenMANIPULATOR code to connect via assigned port.

**Comment by suyunas** [comment]
i am not using U2D2. It seems that U2D2 is required to run the manipulator to establish a remote connection. Is there anyways i can control manipulator using the following strategy:

Remote PC--->RPi----->OpenCR---->Manipulator X???

**Comment by ROBOTIS-Will** [comment]
Have you read this TurtleBot3 Manipulation eManual before?
https://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation/#manipulation

**Comment by suyunas** [comment]
yes i checked the manual. Basically the gui function called for open-manipulator +tb3 has missing drawing circle rhombas and line etc as shown in figure below:
/home/trustai/Pictures/12

I need to make use of those function.

**Comment by suyunas** [comment]
yes i checked the emanual. Apparently the drawing and option tabs are available on the gui called for openmanipulator-X connected through openCR only as shown in figure below:

![test](https://user-images.githubusercontent.com/81650263/115951024-73577480-a4d6-11eb-90d7-d3bca0b75239.png)

These tabs are not available on the gui called for openmanipulator-X connected through turtlebot3,
![13](https://user-images.githubusercontent.com/81650263/115951262-b108cd00-a4d7-11eb-87c7-95cfeb7fc410.jpg)
 i am using the later setup.

**Comment by ROBOTIS-Will** [comment]
Both GUI software works in the same way.
You just need to send a proper topic so from your PC to control the OpenMANIPULATOR.
Since all hardware in ROS1 are connected in the same network, you don't necessarily have to deliver the topic from PC to RPi to OpenCR.

**Comment by suyunas** [comment]
Basically i was trying to explore different options for the project. I will look into other ways for calling those functionalities.
