### ISSUE TITLE
TurtleBot3 Home Service Challenge

### ISSUE THREAD

**Issue by suyunas** [ROBOTIS-GIT/open_manipulator#206]
Whilst doing the TurtleBot3 Home Service Challenge. https://emanual.robotis.com/docs/en/platform/turtlebot3/home_service_challenge/
@ 7.10.3.1. 
I am having the following error:
![Screenshot from 2021-04-24 08-38-20](https://user-images.githubusercontent.com/81650263/115951395-75bace00-a4d8-11eb-9ee7-4ef554bf6783.png)

Remote PC side:
#!/bin/bash
argc=$#
args=("$@")
if [ 0 -eq $argc ]
then
  echo "need to argument that host ip for ssh connection"
  echo "Usage: $0 [ip address] ..."
  exit 1
fi
for((index = 0; index < $#; index++ ))
do
  ssh-keygen -R ${args[$index]}
  ssh-keyscan ${args[$index]} >> ~/.ssh/known_hosts
done

Turtlebot3 side:
#!/bin/bash
#check if other turtlebot3_core is already running
is_running=`ps ax | grep turtlebot3_core`
IFS=' ' read -ra is_runnings <<< "$is_running"
process_name=${is_runnings[4]}
if [ ${process_name} == "python" ]
then
  echo "other turtlebot3_core is already running."
  exit 1
fi

source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash

ip_address=`hostname -I`
ip_address_trim=${ip_address%% * }
ip_address_no_space="$(echo -e "${ip_address_trim}" | tr -d '[:space:]')"
export ROS_HOSTNAME=${ip_address_no_space}

export TURTLEBOT3_MODEL=waffle_pi
exec "$@"

Somebody can help?

**Comment by ROBOTIS-Will** [comment]
Have you run belows from your Remote PC?
```bash
$ chmod +x ~/tb3_ssh_keygen
$ ~/tb3_ssh_keygen 192.168.1.10
```
and the below from your Raspberry Pi on TurtleBot3?
```bash
$ chmod +x ~/env.bash
```
Did you get any warning or error messages when running the above?

**Comment by suyunas** [comment]
![today](https://user-images.githubusercontent.com/81650263/116075296-b0646800-a68a-11eb-9048-ecb9c07aed40.png)
[Remote PC]
Upper left: 
$ roscore

[Pi]
Upper right:
$ roslaunch turtlebot3_bringup turtlebot3_robot.launch

[Remote PC]
Middle left:
$ export TURTLEBOT3_MODEL=${TB3_MODEL}
$ roslaunch turtlebot3_manipulation_description turtlebot3_manipulation_view.launch use_gui:=true

[Remote PC]
Middle right:
$ nano ~/tb3_ssh_keygen
$ chmod +x ~/tb3_ssh_keygen
$ ~/tb3_ssh_keygen 192.168.43.191

[Pi]
Lower left:
$ nano ~/env.bash
$ chmod +x ~/env.bash

[Remote PC]
Lower right:
$ roslaunch turtlebot3_home_service_challenge_tools turtlebot3_pi_cam_remote.launch address:=192.168.43.220

**Comment by ROBOTIS-Will** [comment]
when running the `tb3_ssh_keygen` command, you should use the IP address of TurtleBot3 SBC as below.

[Remote PC]
Middle right:
```bash
$ nano ~/tb3_ssh_keygen
$ chmod +x ~/tb3_ssh_keygen
$ ~/tb3_ssh_keygen 192.168.43.220
```

**Comment by suyunas** [comment]
Apologies in typing i put  ~/tb3_ssh_keygen 192.168.43.191. However from the picture above it is clear that i have used ~/tb3_ssh_keygen 192.168.43.220. Kindly check

**Comment by ROBOTIS-Will** [comment]
@suyunas 
I've tested with my Kinetic setup, but couldn't reproduce the issue.
Have you set the ROS_MASTER_URI and ROS_HOSTNAME for both Remote PC and Raspberry Pi?
[](https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/#network-configuration)

**Comment by suyunas** [comment]
nano ~/.bashrc configurations for Remote PC:
alias eb='nano ~/.bashrc'
alias sb='source ~/.bashrc'
alias gs='git status'
alias gp='git pull'
alias cw='cd ~/catkin_ws'
alias cs='cd ~/catkin_ws/src'
alias cm='cd ~/catkin_ws && catkin_make'
source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash
export ROS_MASTER_URI=http://192.168.43.191:11311
export ROS_HOSTNAME=192.168.43.191
export TURTLEBOT3_MODEL=waffle_pi

TB3:
alias gp='git pull'
alias cw='cd ~/catkin_ws'
alias cs='cd ~/catkin_ws/src'
alias cm='cd ~/catkin_ws && catkin_make'
source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash
export ROS_MASTER_URI=http://192.168.43.191:11311
export ROS_HOSTNAME=192.168.43.220

**Comment by ROBOTIS-Will** [comment]
@suyunas 
Your network configuration looks correct.
> 'Be sure Remote PC and TurtleBot3 are connected under the same IP'. This statement is a bit confusing on Home Service Challenge. how can we keep IP same for two separate devices?

Sorry about the confusion. This means to configure your IP address in the same IP range, such as 192.168.43.xxx

TB3 HSC is currently supported with Kinetic which runs on Ubuntu 16.04 or the provided Raspbian OS image from us.

Please try below command and let me know. This will copy the SSH key to TurtleBot3 SBC.
```bash
$ ssh-copy-id pi@192.168.43.220
```

**Comment by suyunas** [comment]
can be seen in the middle right:
![Screenshot from 2021-04-30 11-04-17](https://user-images.githubusercontent.com/81650263/116680689-e0ba4800-a9a3-11eb-91a9-6e222ae86cf4.png)

**Comment by yun-goon** [comment]
@suyunas Apologies for the delayed response. We have assembled a TF team to address OpenManipulator-x issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
