### ISSUE TITLE
ROS2 simulation, perceptions and Controls

### ISSUE THREAD

**Issue by sardanian** [ROBOTIS-GIT/open_manipulator#210]
Hi there,

I was wondering if the simulation, perceptions (camera) and/or controls packages would be included with the new ROS2 versions coming out this month.

Thank you

**Comment by ROBOTIS-Will** [comment]
Hi @sardanian 
The very basic features to operate the manipulator will be updated first, then other examples or applications (such as perceptions) might be scheduled for the update based on users feedback and internal review.
Thank you.

**Comment by yun-goon** [comment]
Hi, @sardanian 

Thank you for your inquiry.

This issue will be closed as new packages have been uploaded. The perception packages are scheduled to be updated soon.

Please try again with the Humble or Noetic versions, and if the issue persists, feel free to reopen it.
