### ISSUE TITLE
Missing file - dynamixel_workbench.h

### ISSUE THREAD

**Issue by MorrieG** [ROBOTIS-GIT/open_manipulator#22]
I am working from ROS_Robot_Programing_EN.pdf Cahpter 13.2.2 Manipulator Modeling

After cloning as follows;  git clone https://github.com/ROBOTIS-GIT/open_manipulator.git

Then performing; cd ~/catkin_ws && catkin_make

I obtain the following error; [ 98%] Built target ros_tutorials_action_generate_messages
In file included from /home/mozza/catkin_ws/src/open_manipulator/open_manipulator_dynamixel_ctrl/src/dynamixel_controller.cpp:19:0:
/home/mozza/catkin_ws/src/open_manipulator/open_manipulator_dynamixel_ctrl/include/open_manipulator_dynamixel_ctrl/dynamixel_controller.h:24:61: fatal error: dynamixel_workbench_toolbox/dynamixel_workbench.h: No such file or directory
compilation terminated.

System is Ubuntu 16.04 with ROS Kinetic

I cannot locate the above file in either /opt/ros/* or ~/catkin_ws/src/open_manipulator

**Comment by routiful** [comment]
Hi :)

Thank you for your inquiry
You need to download latest version of [dynamixel_workbench_toolbox](https://github.com/ROBOTIS-GIT/dynamixel-workbench).

Thanks
Darby

**Comment by MorrieG** [comment]
Thanks
