### ISSUE TITLE
open manipulator controller Failed

### ISSUE THREAD

**Issue by CristianKmas** [ROBOTIS-GIT/open_manipulator#220]
Hi..
groupSyncRead getdata failed with open manipulator x (Dynamixel 430-w350-T)
I'm using ROS Kinetic 
![SyncRead getdata failed](https://user-images.githubusercontent.com/90069875/132247086-7ff52ac4-db6b-4ea9-b8b4-0f6f5e1975af.jpg)

**Comment by ROBOTIS-Will** [comment]
Hi @CristianKmas 
I'm sorry about the delayed response.
Have you set the read/write permission to the Serial port where the U2D2 is connected at?
https://emanual.robotis.com/docs/en/platform/openmanipulator_x/quick_start_guide/#communication-interface
