### ISSUE TITLE
rviz crashes when motion planning is initialized in turtlebot3_home_service_challenge_demote_remote.launch - kinetic-devel

### ISSUE THREAD

**Issue by meard** [ROBOTIS-GIT/open_manipulator#227]
The branch for the repo is kinetic-devel.
When urtlebot3_home_service_challenge_demote_remote.launch is run, the rviz and navigation functionality works fine. However, when motion planning is initialized in rviz to operate openmanipulator, it shows no transform available between frame error and crash
![Screenshot from 2022-03-04 01-29-42](https://user-images.githubusercontent.com/40901420/156676588-442f8eb0-da49-4dca-a7fd-cddd4405fe36.png)
es.

**Comment by yun-goon** [comment]
@meard Apologies for the delayed response. We have assembled a TF team to address OpenManipulator-x issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
