### ISSUE TITLE
Gazebo for Ros2?

### ISSUE THREAD

**Issue by sardanian** [ROBOTIS-GIT/open_manipulator#228]
When is Gazebo for Ros2 supposed to be implemented? The emanual mentions Q4 2021.

Also, is there a timeframe for MoveIt,  Gravity Compensation and GUI? The emanual says "not supported yet" which makes me think it is on the way but not there yet.

**Comment by EndlessLoops** [comment]
Same question.

**Comment by yun-goon** [comment]
@sardanian Apologies for the delayed response. We have assembled a TF team to address OpenManipulator-x issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
