### ISSUE TITLE
Quite a few typos or information not relavent to Ros2

### ISSUE THREAD

**Issue by sardanian** [ROBOTIS-GIT/open_manipulator#229]
I just wanted to point out a few mistakes in the foxy documention.

This command:
ros2 run open_manipulator_x_teleop open_manipulator_x_teleop_keyboard

should be:
ros2 run open_manipulator_x_teleop teleop_keyboard

This page: https://emanual.robotis.com/docs/en/platform/openmanipulator_x/quick_start_guide/#install-ubuntu-on-pc
Shows usage of ros vs ros2 in section 4.1.4.2
Selction 4.1.3 refers to a robotis_ws folder but the install script in 4.1.2 creates a colon_ws as the build folder

Its working well so far though.

Thank you.

**Comment by ROBOTIS-David** [comment]
Thank you for raising an issue regarding the typo and some misleading content, I will have our engineers check it and make a change on your request.  

* Please allow me to transfer to the proper repos. This issue belongs to another branch, OpenManipulator-X.

**Comment by ashekim** [comment]
Hi @sardanian. 
This content will be corrected and reflected in the e-manual soon.
Thank you for your contribution!

@ROBOTIS-David 
Please update the e-manual after checking the revisions.

**Comment by ROBOTIS-David** [comment]
Thank you for checking this out.
The given PR is confirmed and has been merged to the Master branch of e-Manual . Please close the ticket if solved.

**Comment by yun-goon** [comment]
This issue appears to be resolved, so it will be closed.
