### ISSUE TITLE
lewansoul learm ROS2?

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/open_manipulator#230]
Hello I am a beginner, could I use lewansoul learm for ros2 implementation?

**Comment by ROBOTIS-Will** [comment]
Hi @GrozaGabriel 

We're not the manufacturer of the lewansoul.
Please contact the manufacturer to find out whether their product supports ROS2.
If their product support ROS2 environment, they should have some [instructions like our OpenMANIPULATOR-X](https://emanual.robotis.com/docs/en/platform/openmanipulator_x/quick_start_guide/)

Thank you.

**Comment by yun-goon** [comment]
This issue appears to be resolved, so it will be closed.
