### ISSUE TITLE
forward/backward etc do not function specifically

### ISSUE THREAD

**Issue by sardanian** [ROBOTIS-GIT/open_manipulator#232]
I am testing out the open manipulator in foxy 2 and when I move the arm forward/backward etc, it dips down, slowly reaching the bottom vs. keeping the same consistent height as I assume is intended. I seem to remember when using ROS melodic that it stayed at a consistent height.

Is this a flaw in foxy or is this a problem that has started to occur in my arm?

Additionally, if I wanted to debug/fix this issue, where in the code should I do this and is there any documentation to help me along the way?

I'd also love to change my toolhead to a different type of gripper that I am making and would love to understand what parts I should change

Thank you.

**Comment by yun-goon** [comment]
Apologies for the delayed response. We have assembled a TF team to address OpenManipulator-x issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
