### ISSUE TITLE
Master / Slave functions for foxy

### ISSUE THREAD

**Issue by sardanian** [ROBOTIS-GIT/open_manipulator#234]
Are these expected to be released any time soon? The emanual mentions it will be released in Q4 of 2021.

**Comment by yun-goon** [comment]
@sardanian Thank you for your interest in contributing to open source and for your enthusiasm in building a career in robotics. We genuinely appreciate your offer to contribute to this repository.

However, as of 2022, we have significantly reduced our active management of this open platform. While we are in the process of forming an open-source TF team to handle outstanding issues, this repository is not currently a priority for us. Given these circumstances, we may not be able to provide the level of support and collaboration necessary for meaningful contributions at this time.

We recommend exploring other actively maintained robotics projects or repositories where your efforts can have a more immediate and impactful contribution. Your passion and initiative are commendable, and we encourage you to continue pursuing open source opportunities within the robotics community. Thank you again for your understanding and interest.
