### ISSUE TITLE
It doesn't move in the direction id11 is responsible for.

### ISSUE THREAD

**Issue by kimjunho654** [ROBOTIS-GIT/open_manipulator#238]
I assembled the manipulator with xl430 w250. I set the id of each motor and set the baud rate to 1 mbps. But it's out of control. Are there any other values that need to be changed? It's a melodic environment. Now that I follow the manual, the robot arm moves up and down, back and forth, but it does not move in the direction of id11. Also, if you apply it in that direction with rviz, the computer will stop.  
 
![KakaoTalk_20220902_191908477](https://user-images.githubusercontent.com/105560901/188118915-1b104f39-1674-4ae4-8aed-c091f9d571bf.jpg)

**Comment by yun-goon** [comment]
@kimjunho654 Apologies for the delayed response. We have assembled a TF team to address OpenManipulator-x issues and are actively working on resolutions. Please note that we do not support EOL (End-of-Life) ROS versions; our support currently extends to Noetic and Humble versions. We kindly ask that you try again with the latest version. If the same issue arises, please feel free to resubmit it, and we will address it promptly.
