### ISSUE TITLE
openmanipulator-x simulation using ros2 foxy

### ISSUE THREAD

**Issue by ssapssabi** [ROBOTIS-GIT/open_manipulator#259]
hi. i'm trying to simulate openmanipulator-x using ros2 foxy.
and i'm looking for manual about foxy. but on robotis e-manual,
but on robotis e-manual page, they said it will be coming soon on 2021 4Q. 
so i wonder that when can i check e-menual about openmanipulaor-x using ros2 foxy.
Thank you. and sorry for my bad engilsh.

**Comment by shiba-8ro** [comment]
@ssapssabi 
Hi, Is the Turtlebot3 with OpenMANIPUATOR-X e-manual helpful for you?
https://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation/#simulation

**Comment by ssapssabi** [comment]
I will check it! Thank you for your help!!
