### ISSUE TITLE
catkin_make failed

### ISSUE THREAD

**Issue by j1406493495** [ROBOTIS-GIT/open_manipulator#40]
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "open_manipulator_msgs" with any of the following names:

**Comment by j1406493495** [comment]
make success when clone msgs and checkout branch

**Comment by Pointcloud-Rob** [comment]
Hello, Robotis team, I ran into the same issue when building the open_manipulator package.  Have you restructured the package/metapackage to pull open_manipulator_messages out?

Would you update http://wiki.ros.org/open_manipulator to show "open_manipulator_msgs" as a dependency
