### ISSUE TITLE
[betaTest][5.Bringup]About sample code

### ISSUE THREAD

**Issue by t-kitajima** [ROBOTIS-GIT/open_manipulator#42]
hi,

I build an OpenManipulator according to e-manual.
http://emanual.robotis.com/docs/en/platform/openmanipulator/#hardware-setup

The Dynamixel ID of sample code (**5.Bringup**) is still 1 to 5.
The Dynamixel ID of master  code is 11 to 15.

When assembling according to **3.3.Assembly Manual**, if Dyanamixel ID of **.launch file** is 1 to 5, an error will result.

[ERROR] [1539839180.453643113]: Not found Joints, Please check id and baud rate
REQUIRED process [dynamixel_controller-2] has died!
process has finished cleanly
log file: /home/kitajima/.ros/log/8ca3ba38-d293-11e8-9bf1-d46d6d3132ab/dynamixel_controller-2*.log
Initiating shutdown!

I propose to change the ID of sample code of **5.Bringup** to 11 ~ 15.

**Comment by routiful** [comment]
Thank you for your contribution!
I opened PR https://github.com/ROBOTIS-GIT/emanual/pull/499. It will be updated.

**Comment by t-kitajima** [comment]
I confirmed that the e-manual was updated.
http://emanual.robotis.com/docs/en/platform/openmanipulator/#hardware-setup

Thank you.

**Comment by routiful** [comment]
Good :) If you have any further issue, please feel free to open issue.
