### ISSUE TITLE
MoveIT Controller Issue

### ISSUE THREAD

**Issue by fatihirim** [ROBOTIS-GIT/open_manipulator#59]
Hello 
When I try to launch open_manipulator_moveit_controller via following command on Ubuntu 16.04:
roslaunch open_manipulator_moveit_controller open_manipulator_moveit.launch

I get following error:

started roslaunch server http://robut-linux-1:40703/

SUMMARY
========

PARAMETERS
 * /arm_controller/init_position: False
 * /gazebo: False
 * /joint_state_publisher/source_list: ['open_manipulato...
 * /joint_state_publisher/use_gui: False
 * /move_group/allow_trajectory_execution: False
 * /move_group/arm/default_planner_config: RRTConnect
 * /move_group/arm/longest_valid_segment_fraction: 0.005
 * /move_group/arm/planner_configs: ['SBL', 'EST', 'L...
 * /move_group/arm/projection_evaluator: joints(joint1,joi...
 * /move_group/capabilities: 
 * /move_group/disable_capabilities: 
 * /move_group/gripper/default_planner_config: 
 * /move_group/gripper/longest_valid_segment_fraction: 0.005
 * /move_group/gripper/planner_configs: ['SBL', 'EST', 'L...
 * /move_group/gripper/projection_evaluator: joints(grip_joint...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_safe_path_cost: 1
 * /move_group/planner_configs/BFMT/balanced: 0
 * /move_group/planner_configs/BFMT/cache_cc: 1
 * /move_group/planner_configs/BFMT/extended_fmt: 1
 * /move_group/planner_configs/BFMT/heuristics: 1
 * /move_group/planner_configs/BFMT/nearest_k: 1
 * /move_group/planner_configs/BFMT/num_samples: 1000
 * /move_group/planner_configs/BFMT/optimality: 1
 * /move_group/planner_configs/BFMT/radius_multiplier: 1.0
 * /move_group/planner_configs/BFMT/type: geometric::BFMT
 * /move_group/planner_configs/BKPIECE/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECE/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECE/range: 0.0
 * /move_group/planner_configs/BKPIECE/type: geometric::BKPIECE
 * /move_group/planner_configs/BiEST/range: 0.0
 * /move_group/planner_configs/BiEST/type: geometric::BiEST
 * /move_group/planner_configs/BiTRRT/cost_threshold: 1e300
 * /move_group/planner_configs/BiTRRT/frountier_node_ratio: 0.1
 * /move_group/planner_configs/BiTRRT/frountier_threshold: 0.0
 * /move_group/planner_configs/BiTRRT/init_temperature: 100
 * /move_group/planner_configs/BiTRRT/range: 0.0
 * /move_group/planner_configs/BiTRRT/temp_change_factor: 0.1
 * /move_group/planner_configs/BiTRRT/type: geometric::BiTRRT
 * /move_group/planner_configs/EST/goal_bias: 0.05
 * /move_group/planner_configs/EST/range: 0.0
 * /move_group/planner_configs/EST/type: geometric::EST
 * /move_group/planner_configs/FMT/cache_cc: 1
 * /move_group/planner_configs/FMT/extended_fmt: 1
 * /move_group/planner_configs/FMT/heuristics: 0
 * /move_group/planner_configs/FMT/nearest_k: 1
 * /move_group/planner_configs/FMT/num_samples: 1000
 * /move_group/planner_configs/FMT/radius_multiplier: 1.1
 * /move_group/planner_configs/FMT/type: geometric::FMT
 * /move_group/planner_configs/KPIECE/border_fraction: 0.9
 * /move_group/planner_configs/KPIECE/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECE/goal_bias: 0.05
 * /move_group/planner_configs/KPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECE/range: 0.0
 * /move_group/planner_configs/KPIECE/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECE/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECE/range: 0.0
 * /move_group/planner_configs/LBKPIECE/type: geometric::LBKPIECE
 * /move_group/planner_configs/LBTRRT/epsilon: 0.4
 * /move_group/planner_configs/LBTRRT/goal_bias: 0.05
 * /move_group/planner_configs/LBTRRT/range: 0.0
 * /move_group/planner_configs/LBTRRT/type: geometric::LBTRRT
 * /move_group/planner_configs/LazyPRM/range: 0.0
 * /move_group/planner_configs/LazyPRM/type: geometric::LazyPRM
 * /move_group/planner_configs/LazyPRMstar/type: geometric::LazyPR...
 * /move_group/planner_configs/PDST/type: geometric::PDST
 * /move_group/planner_configs/PRM/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRM/type: geometric::PRM
 * /move_group/planner_configs/PRMstar/type: geometric::PRMstar
 * /move_group/planner_configs/ProjEST/goal_bias: 0.05
 * /move_group/planner_configs/ProjEST/range: 0.0
 * /move_group/planner_configs/ProjEST/type: geometric::ProjEST
 * /move_group/planner_configs/RRT/goal_bias: 0.05
 * /move_group/planner_configs/RRT/range: 0.0
 * /move_group/planner_configs/RRT/type: geometric::RRT
 * /move_group/planner_configs/RRTConnect/range: 0.0
 * /move_group/planner_configs/RRTConnect/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTstar/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstar/goal_bias: 0.05
 * /move_group/planner_configs/RRTstar/range: 0.0
 * /move_group/planner_configs/RRTstar/type: geometric::RRTstar
 * /move_group/planner_configs/SBL/range: 0.0
 * /move_group/planner_configs/SBL/type: geometric::SBL
 * /move_group/planner_configs/SPARS/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARS/max_failures: 1000
 * /move_group/planner_configs/SPARS/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARS/stretch_factor: 3.0
 * /move_group/planner_configs/SPARS/type: geometric::SPARS
 * /move_group/planner_configs/SPARStwo/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARStwo/max_failures: 5000
 * /move_group/planner_configs/SPARStwo/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARStwo/stretch_factor: 3.0
 * /move_group/planner_configs/SPARStwo/type: geometric::SPARStwo
 * /move_group/planner_configs/STRIDE/degree: 16
 * /move_group/planner_configs/STRIDE/estimated_dimension: 0.0
 * /move_group/planner_configs/STRIDE/goal_bias: 0.05
 * /move_group/planner_configs/STRIDE/max_degree: 18
 * /move_group/planner_configs/STRIDE/max_pts_per_leaf: 6
 * /move_group/planner_configs/STRIDE/min_degree: 12
 * /move_group/planner_configs/STRIDE/min_valid_path_fraction: 0.2
 * /move_group/planner_configs/STRIDE/range: 0.0
 * /move_group/planner_configs/STRIDE/type: geometric::STRIDE
 * /move_group/planner_configs/STRIDE/use_projected_distance: 0
 * /move_group/planner_configs/TRRT/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRT/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRT/goal_bias: 0.05
 * /move_group/planner_configs/TRRT/init_temperature: 10e-6
 * /move_group/planner_configs/TRRT/k_constant: 0.0
 * /move_group/planner_configs/TRRT/max_states_failed: 10
 * /move_group/planner_configs/TRRT/min_temperature: 10e-10
 * /move_group/planner_configs/TRRT/range: 0.0
 * /move_group/planner_configs/TRRT/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRT/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: industrial_trajec...
 * /move_group/sample_duration: 0.01
 * /move_group/smoothing_5_coef: [0.25, 0.5, 1.0, ...
 * /move_group/smoothing_filter_name: /move_group/smoot...
 * /move_group/start_state_max_bounds_error: 0.1
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/arm/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/arm/kinematics_solver_attempts: 3
 * /robot_description_kinematics/arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/arm/kinematics_solver_timeout: 0.005
 * /robot_description_kinematics/arm/position_only_ik: False
 * /robot_description_planning/joint_limits/grip_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/grip_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/grip_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/grip_joint/max_velocity: 3.5
 * /robot_description_planning/joint_limits/grip_joint_sub/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/grip_joint_sub/has_velocity_limits: True
 * /robot_description_planning/joint_limits/grip_joint_sub/max_acceleration: 0
 * /robot_description_planning/joint_limits/grip_joint_sub/max_velocity: 3.5
 * /robot_description_planning/joint_limits/joint1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint1/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint1/max_velocity: 6.5
 * /robot_description_planning/joint_limits/joint2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint2/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint2/max_velocity: 6.5
 * /robot_description_planning/joint_limits/joint3/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint3/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint3/max_velocity: 6.5
 * /robot_description_planning/joint_limits/joint4/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint4/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint4/max_velocity: 6.5
 * /robot_description_semantic: <?xml version="1....
 * /robot_name: open_manipulator
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /rviz_robut_linux_1_21790_1581174226874176874/arm/kinematics_solver: kdl_kinematics_pl...
 * /rviz_robut_linux_1_21790_1581174226874176874/arm/kinematics_solver_attempts: 3
 * /rviz_robut_linux_1_21790_1581174226874176874/arm/kinematics_solver_search_resolution: 0.005
 * /rviz_robut_linux_1_21790_1581174226874176874/arm/kinematics_solver_timeout: 0.005
 * /rviz_robut_linux_1_21790_1581174226874176874/arm/position_only_ik: False

NODES
  /
    arm_controller (open_manipulator_moveit_controller/arm_controller)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_robut_linux_1_21790_1581174226874176874 (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[joint_state_publisher-1]: started with pid [21810]
process[robot_state_publisher-2]: started with pid [21811]
process[move_group-3]: started with pid [21812]
process[rviz_robut_linux_1_21790_1581174226874176874-4]: started with pid [21813]
process[arm_controller-5]: started with pid [21823]
[ INFO] [1543235446.306699129]: rviz version 1.12.16
[ INFO] [1543235446.306746437]: compiled against Qt version 5.5.1
[ INFO] [1543235446.306758034]: compiled against OGRE version 1.9.0 (Ghadamon)
[move_group-3] process has died [pid 21812, exit code -11, cmd /opt/ros/kinetic/lib/moveit_ros_move_group/move_group __name:=move_group __log:=/home/fatih/.ros/log/6868206e-f165-11e8-bc6c-7cb0c2fe1875/move_group-3.log].
log file: /home/fatih/.ros/log/6868206e-f165-11e8-bc6c-7cb0c2fe1875/move_group-3*.log
[ INFO] [1543235446.967647496]: Stereo is NOT SUPPORTED
[ INFO] [1543235446.967910198]: OpenGl version: 3 (GLSL 1.3).
[rviz_robut_linux_1_21790_1581174226874176874-4] process has died [pid 21813, exit code -11, cmd /opt/ros/kinetic/lib/rviz/rviz -d /home/fatih/WORKSPACES/ws_open_manipulator/src/open_manipulator/open_manipulator_moveit/launch/moveit.rviz __name:=rviz_robut_linux_1_21790_1581174226874176874 __log:=/home/fatih/.ros/log/6868206e-f165-11e8-bc6c-7cb0c2fe1875/rviz_robut_linux_1_21790_1581174226874176874-4.log].
log file: /home/fatih/.ros/log/6868206e-f165-11e8-bc6c-7cb0c2fe1875/rviz_robut_linux_1_21790_1581174226874176874-4*.log
================================================================================REQUIRED process [arm_controller-5] has died!
process has died [pid 21823, exit code -11, cmd /home/fatih/WORKSPACES/ws_open_manipulator/devel/lib/open_manipulator_moveit_controller/arm_controller __name:=arm_controller __log:=/home/fatih/.ros/log/6868206e-f165-11e8-bc6c-7cb0c2fe1875/arm_controller-5.log].
log file: /home/fatih/.ros/log/6868206e-f165-11e8-bc6c-7cb0c2fe1875/arm_controller-5*.log
Initiating shutdown!

================================================================================
[arm_controller-5] killing on exit
[robot_state_publisher-2] killing on exit
[joint_state_publisher-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

What might be the problem?

Thanks in advance

**Comment by routiful** [comment]
You should launch open_manipulator_controller first
Please follow below instruction

http://emanual.robotis.com/docs/en/platform/openmanipulator/#manipulation

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
