### ISSUE TITLE
Unable to control Open manipulator via OpenCR

### ISSUE THREAD

**Issue by LJM2018** [ROBOTIS-GIT/open_manipulator#82]
Hello, I was following the emanual on your website in order to get the manipulator working. Everything seems fine before step 8.4, Basic Manipulation on OpenCR (http://emanual.robotis.com/docs/en/platform/openmanipulator/#basic-manipulation-on-opencr). The only issue happened was in the step 4 I wasn't able to launch the open manipulator controller in terminal. The error I got is "[PortHandlerLinux::SetupPort] Error opening serial port!". 

Since I couldn't solve it, I move on to step 8 because I am pretty sure every package has been successfully installed and compiled. However, in step 8.4, after I run the chain.pde code in processing, the manipulator doesn't move at all and all the motors are loose no matter how I change the setting in control panel(controller is on). The console showed that "OpenManipulator Ready!!!" but it doesn't work at all. There were also two error messages between "[32] "/dev/ttyS31" and the "OpenManipulator Ready!!!" message. My initial guess was that some connection issue with the port cause this but I was able to upload the open manipulator chain code from arduino IDE to opencr and no error showed up. So I don't know what could cause this. 

Do you have any suggestions? Thanks in advance.

**Comment by LJM2018** [comment]
![image](https://user-images.githubusercontent.com/35580709/51793824-b6053780-217b-11e9-9ff3-bdb56e2e95ff.png)

**Comment by gpwhd07** [comment]
Hello @ LJM2018
Sorry for late reply.
You need to know the test environment.

First, did you upload the example source code (eg OpenManipulator → Example → Chain → open_manipulator_chain) to OpenCR using the Arduino IDE?
The way OpenManipulator is controlled by OpenCR (embedded system) and ROS is completely different. In the method using ROS, the controller runs in PC, but in OpenCR control, the controller runs in OpenCR without ROS. Therefore, the controller example source code mentioned above needs to be uploaded to OpenCR and you do not need to run the ROS controller package.

If you're sure you're running in the above execution environment, the above error message is an error message because it does not recognize the USB port of OpenCR. Make sure that the port to which OpenCR is connected (normally / dev / ttyACM0) is recognized correctly. This port can be found on the ArduinoIDE.

If the connected port is not /dev/ttyACM0, or on the port list of the message when Processing is executed the port to which your OpenCR is connected is not [0], 

```
[0] "/ dev / ttyACM0"
[1] "/ dev / ttyS0"
[2] "/ dev / ttyS1"
[3] "/ dev / ttyS2"
```

you may need to modify the code in **line 78** of Processing source code.

`[connectOpenCR (0); // It is depend on laptop enviroments]`

You must change the number in the above sentence to the number of the recognized port in the above list.

**Comment by LJM2018** [comment]
Thanks for your reply! I have followed your instructions but it still doesn't work. On the Arduino IDE interface, it shows that the port is /dev/ttyACM0. And on the port list of the message when Processing is executed, it shows something just like what you mentioned. The first line is /dev/ttyACM0 and no error shows this time. However, the manipulator still loose. I am pretty sure the source code has been uploaded but when I tried to upload it again, it gave me error "cmd_read_board_name fail : 0xF020". Then when I tried to burn the boot loader, I got error saying "No DFU capable USB device available" but in the terminal I can find dev/ttyACM0 using ls -la /dev/ttyACM*. 

Here are all the error messages I received.

![image](https://user-images.githubusercontent.com/35580709/51953296-b2c6b180-23f0-11e9-938b-bde68281ed1c.png)
![image](https://user-images.githubusercontent.com/35580709/51953315-ca9e3580-23f0-11e9-817b-495d2274df34.png)

![image](https://user-images.githubusercontent.com/35580709/51953177-37650000-23f0-11e9-98be-13c4bb0792f2.png)
![image](https://user-images.githubusercontent.com/35580709/51953218-624f5400-23f0-11e9-9a8b-86fc1deb9db1.png)
![image](https://user-images.githubusercontent.com/35580709/51953372-f91c1080-23f0-11e9-8d86-36d826804011.png)
![image](https://user-images.githubusercontent.com/35580709/51953383-0638ff80-23f1-11e9-984c-3831b17cfbf2.png)

**Comment by gpwhd07** [comment]
Hi again, 

This error seems to occur because the controller source code is not uploaded correctly to OpenCR.

Please refer to [OpenCR e-manual](http://emanual.robotis.com/docs/en/parts/controller/opencr10/#writing-bootloaderlinux) to re-write the boot loader. 
Please try uploading the source again.

**Comment by gpwhd07** [comment]
In addition, if an error of cmd_read_board_name fail: 0xF020 occurs constantly during upload, please refer to [OpenCR e-manual](http://emanual.robotis.com/docs/en/parts/controller/opencr10/#firmware-recovery-mode) to recover OpenCR Please try uploading again after entering mode.

**Comment by LJM2018** [comment]
Thanks again. I tried re-write the bootloader and reinstall the firmware (using shell command) while the OpenCR board is in recovery mode. However, I can't upload any code to it because it shows the error message below:

Arduino: 1.8.7 (Linux), Board: "OpenCR Board, OpenCR Bootloader"

/home/nsfnri/tools/arduino-1.8.7/arduino-builder -dump-prefs -logger=machine -hardware /home/nsfnri/tools/arduino-1.8.7/hardware -hardware /home/nsfnri/.arduino15/packages -tools /home/nsfnri/tools/arduino-1.8.7/tools-builder -tools /home/nsfnri/tools/arduino-1.8.7/hardware/tools/avr -tools /home/nsfnri/.arduino15/packages -built-in-libraries /home/nsfnri/tools/arduino-1.8.7/libraries -libraries /home/nsfnri/Arduino/libraries -fqbn=OpenCR:OpenCR:OpenCR:upload_method=UploadMethod -ide-version=10807 -build-path /tmp/arduino_build_617417 -warnings=none -build-cache /tmp/arduino_cache_434609 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.opencr_tools.path=/home/nsfnri/.arduino15/packages/OpenCR/tools/opencr_tools/1.0.0 -prefs=runtime.tools.opencr_tools-1.0.0.path=/home/nsfnri/.arduino15/packages/OpenCR/tools/opencr_tools/1.0.0 -prefs=runtime.tools.opencr_gcc.path=/home/nsfnri/.arduino15/packages/OpenCR/tools/opencr_gcc/5.4.0-2016q2 -prefs=runtime.tools.opencr_gcc-5.4.0-2016q2.path=/home/nsfnri/.arduino15/packages/OpenCR/tools/opencr_gcc/5.4.0-2016q2 -verbose /home/nsfnri/.arduino15/packages/OpenCR/hardware/OpenCR/1.3.2/libraries/OpenManipulator/example/Arduino/Chain/open_manipulator_chain/open_manipulator_chain.ino

Board OpenCR (platform OpenCR, package OpenCR) is unknown

Error compiling for board OpenCR Board.
![image](https://user-images.githubusercontent.com/35580709/52029102-a3199c80-24c6-11e9-9f13-7877b4e6c3be.png)

I thought it was the DFU mode that caused it but it still didn't work after I pushed the reset button. 

Also, when I try to update the board to the latest version(1.4.1)using the board manager in Arduino. It always goes back to V1.3.2 after I try uploading any code.(Also prompt that sketch folder disappear..)

![image](https://user-images.githubusercontent.com/35580709/52029226-2cc96a00-24c7-11e9-8570-5b48602c9451.png)

![image](https://user-images.githubusercontent.com/35580709/52029238-3fdc3a00-24c7-11e9-8102-ed5a87c024d6.png)

I got lost after getting these errors and I couldn't find anything relate to this online. Could you give me some suggestions? Thanks!

**Comment by gpwhd07** [comment]
Hi, again, 
Looking at the current status, it seems that the OpenCR Board path is connected incorrectly.
 
Open the 'file'-> 'preferences' in the Arduino IDE and click a link  (eg, /home/robotis/.arduino15/preferences.txt) at bottom of the preferences window, then it will enter the .arduino15 folder.
Delete the 'OpenCR' folder in 'package' folder.
After that, reinstall OpenCR again from Tools -> Board -> Boards Maniger ..

If this does not solve the problem, we recommend reinstalling the arduinoi IDE.

**Comment by LJM2018** [comment]
Oh, sorry for the late update. I have already figure out to install firmware successfully. However, even though there is no error anymore while uploading the code and run the chain.pde using processing IDE, the manipulator still couldn't move and totally loose. I suspect there is something wrong with the way I connect all the cable. So currently, there is only one four-pin cable from the bottom actuator to the OpenCR(Other actuators are connected one by one). Also, when I set ID for these motor, I set them to 1~4(without gripper installed). For the baud rate, they were not the same initially, so I set them all to the default(57600). According to the Robo Manager Plus, there are two XM430-W350 and two XM430-W210 motors. I am not sure if I should set their baud rate the same. Could you give me some instructions regarding the motor ID, baud rate and the hardware setting? I couldn't find anything related to hardware connection on your website. Thanks!

**Comment by LJM2018** [comment]
> Hi, again,
> Looking at the current status, it seems that the OpenCR Board path is connected incorrectly.
>  
> Open the 'file'-> 'preferences' in the Arduino IDE and click a link (eg, /home/robotis/.arduino15/preferences.txt) at bottom of the preferences window, then it will enter the .arduino15 folder.
> Delete the 'OpenCR' folder in 'package' folder.
> After that, reinstall OpenCR again from Tools -> Board -> Boards Maniger ..
> 
> If this does not solve the problem, we recommend reinstalling the arduinoi IDE.

I did reinstall the Arduino IDE and update it to the latest version(1.8.8) and it solves the issue. However, the manipulator won't move. I have made a comment about the detail of my problems. Thank you for your help!

**Comment by LJM2018** [comment]
Thanks for your suggestions! The manipulator is no longer loose when I turn on the controller. However, it still won't move after I clicked "send Joint angle". Do you know what could cause this?

Since this method still doesn't work, I tried controlling the manipulator by ROS. However, the console prompts me error message "[TxRxResult]There is no status packet!" "Please check your Dynamixel ID" "[DynamixelDriver] Failed to get the Tool". I have set all four actuators ID to 11-14 from base to gripper(No gripper) so I wonder why it is complaining about the ID.

**Comment by LJM2018** [comment]
I figured it out. Once I connected the gripper motor to the system, everything works fine.

**Comment by userdw** [comment]
How to solve this error, when i want to plan some movement from Rviz with MoveIt the error message always like this
![faile_motion](https://user-images.githubusercontent.com/28077531/63690515-11dd8f00-c837-11e9-9bf5-6d3231d597fd.png)
