### ISSUE TITLE
Joints position are not in sync with simulations

### ISSUE THREAD

**Issue by LJM2018** [ROBOTIS-GIT/open_manipulator#88]
Hello everyone, I was able to control each joint of the open manipulator after I connected the gripper motor to the chain. However, in the simulations(Processing, Rviz), the joints positions are definitely not synced. There is a difference in joint 3(the third actuator counted from the base). Is it a software issue or is it a issue that can be solved by doing calibration with R+ manager? 

![image](https://user-images.githubusercontent.com/35580709/52449908-cad3ba80-2aed-11e9-89e3-17dbb92a2df4.png)

below shows the offset between the actual pose and the wrong calculated pose.

![image](https://user-images.githubusercontent.com/35580709/52450121-9ad8e700-2aee-11e9-932b-db306479ae97.png)

Also, since I couldn't find my calibration adapter, I wonder if there is a STL file that allows me to 3D print it. Thanks in advance.

**Comment by Affonso-Gui** [comment]
Hello,

Are the above images taken in the same timing? (that is, do the Rviz and Processing show the same offset for joint 3, or each one has a different error value?)

Besides the offset, is the Rviz responsive? When you turn off the motors and move the manipulator around is the Rviz model correctly updated? Specially for joint 3, moving it upwards make the joint 3 in the model move in the same direction/ somewhat the same value?

If all the answers are 'yes', then it seems to be an offset problem. Make sure that the zero point of the joint 3 actuator (indicated by a dot in the servo horn) is pointing straight to the next link and that the [homing offset](http://support.robotis.com/en/product/actuator/dynamixel_x/xm_series/xm430-w350.htm#bookmark7) is set to zero.

**Comment by LJM2018** [comment]
> Hello,
> 
> Are the above images taken in the same timing? (that is, do the Rviz and Processing show the same offset for joint 3, or each one has a different error value?)
> 
> Besides the offset, is the Rviz responsive? When you turn off the motors and move the manipulator around is the Rviz model correctly updated? Specially for joint 3, moving it upwards make the joint 3 in the model move in the same direction/ somewhat the same value?
> 
> If all the answers are 'yes', then it seems to be an offset problem. Make sure that the zero point of the joint 3 actuator (indicated by a dot in the servo horn) is pointing straight to the next link and that the [homing offset](http://support.robotis.com/en/product/actuator/dynamixel_x/xm_series/xm430-w350.htm#bookmark7) is set to zero.

Hello  @Affonso-Gui, thanks for your reply!. 

Both Processing and Rviz show the same but wrong configuration of the manipulator. They are all responsive to change of the joint angle.

![image](https://user-images.githubusercontent.com/35580709/52453964-974d5c00-2afe-11e9-86e1-47b4865d3f8a.png)

However,
in Processing IDE, the change value of joint positions updated correctly but the direction is wrong(opposite) for most of the actuators(joint 1 seems correct).
In Rviz, the situation is similar, even though the simulation updated the change of value correctly, the direction of changing joint angle is opposite.

![image](https://user-images.githubusercontent.com/35580709/52454321-3757b500-2b00-11e9-89ad-9e13fc83565f.png)

I wonder if this is due to some installation mistakes because this manipulator is not installed by myself. Do you have any suggestions? Thank you!

**Comment by gpwhd07** [comment]
Hello @LJM2018 
and thanks @Affonso-Gui,

I think this problem is due to installation mistakes such like of installed direction of Dynamixel is wrong.
Please check manipulator installation about specially `dynamixel installation direction` and `Horn Align`, refer to [assembly manual of e-manual](http://emanual.robotis.com/docs/en/platform/openmanipulator/#assembly-manual).

**Comment by LJM2018** [comment]
Thank you so much! @gpwhd07 I just re-assembled it and everything works fine.
