### ISSUE TITLE
How to control turtlebot's wheels and manipulator at the same time?

### ISSUE THREAD

**Issue by LJM2018** [ROBOTIS-GIT/open_manipulator#89]
I was trying to teleop turtlebot3's wheels in order to let it move using "roslaunch turtlebot3_teleop keyboard.launch" after running "roslaunch open_manipulator_with_tb3_tools robot.launch". The OpenCR board is uploaded with open_manipulator_with_tb3_core. However, even though I was able to control the manipulator by doing rosserivce call ....   I wasn't able to let the turtlebot's wheels moving using the above command. Since that command is not actually designed for turtlebot with manipulator, I wonder if there is a better way to control manipulator and turtlebot's wheels (via keyboard..etc).

**Comment by LJM2018** [comment]
I couldn't find any other information about this on the Robotis website.

**Comment by routiful** [comment]
You can find some tutorials to follow emanual
http://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation/#manipulation

**Comment by LJM2018** [comment]
Hello, thanks for the reply. I have read the entire emanual, however, I still couldn't figure out how to control joints of the manipulator when the wheels are controlled at the same time. 

Is there a way to control the manipulator(not just gripper) with "open_manipulator_with_tb3_core" uploaded to turtlebot using **just the terminal**? Because what I saw in the tutorial is only about how to use moveit and its interactive ball to control the manipulator.
![image](https://user-images.githubusercontent.com/35580709/52684542-78363c00-2efb-11e9-83a3-6a761fa3cb2c.png)

(I tired rosservice call /om_with_tb3/.. to control those joints like controlling the gripper but failed)
![image](https://user-images.githubusercontent.com/35580709/52684550-7ff5e080-2efb-11e9-864b-e567b85fbf18.png)

The official tutorial only shows how to control the gripper using Moveit and some task controller but there is almost no information about controlling the other joints. I tried 'rostopic list' as well as 'rosservice list' but I only found some related topics/services about the gripper's **position**, there are nothing related to joint's position.

**Comment by LJM2018** [comment]
Is there a XXX_teleop.launch that can be used to control both wheels and manipulator at the same time?

**Comment by routiful** [comment]
1. OpenCR core has subscriber to control manipulator and gripper. The releated topic names are `/joint_trajectory_point` and `/gripper_position`.

2. When you launch manipulation.launch, `moveit_bridge` node will run as well. This node which includes moveit api will makes planned path to get desired goal. the releated service names are `/moveit/get_joint_position` and `/moveit/get_kinematics_pose`

3. teleop.launch publishes `/cmd_vel` msg only.

**Comment by LJM2018** [comment]
When I launch the moveit (roslaunch open_manipulator_with_tb3_tools manipulation.launch use_platform:=true), I got errors like below and there was no interactive marker on the moveit interface

![image](https://user-images.githubusercontent.com/35580709/52893300-b6c43480-314f-11e9-8d02-92e7ec40710d.png)

![image](https://user-images.githubusercontent.com/35580709/52893380-6dc0b000-3150-11e9-969a-69cdc01332a1.png)

I feel like the moveit isn't completely launched since there is no way to control the manipulator. Do you have any suggestions?

Any suggestion will be appreciated! :)

**Comment by LJM2018** [comment]
> 1. OpenCR core has subscriber to control manipulator and gripper. The releated topic names are `/joint_trajectory_point` and `/gripper_position`.
> 2. When you launch manipulation.launch, `moveit_bridge` node will run as well. This node which includes moveit api will makes planned path to get desired goal. the releated service names are `/moveit/get_joint_position` and `/moveit/get_kinematics_pose`
> 3. teleop.launch publishes `/cmd_vel` msg only.

Thank you for your reply!

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
