### ISSUE TITLE
open_manipulator_dynamixel_controller error message

### ISSUE THREAD

**Issue by orasman** [ROBOTIS-GIT/open_manipulator#9]
Hi~ 
I beginner of ROS.
open_manipulator package is a great reference to start manipulator!
Thanks for ROBOTIS team!

When I follwed dynamixel control example, there is a error as below.

------------------------
 PARAMETERS
  * /baud_rate: 57600
  * /device_name: /dev/ttyUSB0
  * /protocol_version: 1.0
  * /rosdistro: kinetic
  * /rosversion: 1.12.7

 NODES
    /open_manipulator_dynamixel_controller (open_manipulator_dynamixel_ctrl/dynamixel_controller)

  ROS_MASTER_URI=http://localhost:11311

  core service [/rosout] found
  process[open_manipulator_dynamixel_controller-1]: started with pid [11056]
  [ INFO] [1505028572.635044008]: Succeeded to open the port( /dev/ttyUSB0)!
  [ INFO] [1505028572.637931777]: Succeeded to change the baudrate(57600)!
  [ INFO] [1505028572.718853873]: open_manipulator_dynamixel_controller : Init OK!
  [ERROR] [15050228572.718904905]: Sync Read Failed!
  terminate called after throwing an instance of 'std::out_of_range'
    what(): vector::_M_range_check: __n (which is 0) >= the->size() (which is 0)

-----------------------------

"Sync Read Failed!" error message generated from 

from "_Dynamixel_controller.cpp_"
_bool DynamixelController::readDynamixelState(void)_ function

So I made that comment out error generated function.

_bool DynamixelController::control_loop()
{
  // Read & Publish Dynamixel position
  **//readDynamixelState();    //comment out to avoid error message** 
}_

Then it works. so when I click "Plan&Execute" in MoveIt, my dynamixel rotating.

Is this correct way?
If I delete _readDynamixelState();_ , there is no side-effect?

actually, I had only 3 dynamixel, so I changed MAX_DXL_NUM to 3
is this cause of this error message?

from _dynamixel_controller.h_ file
#define MOTOR                             (0)  
#define MAX_DXL_NUM                (3)    //5
#define ITERATION_FREQUENCY  (25)

**Comment by routiful** [comment]
Hi :)

The error message shows out of range of vector size. 
Did you set Dynamixel ID 1, 2, 3 ??

**Comment by orasman** [comment]
Yes, I did.
I set my dynamixel ID as 1,2,3.

**Comment by routiful** [comment]
Oh, you have used protocol 1.0.
Protocol 1.0 doesn't support **sync_read**.
If you want to read present_position of Dynamixel, displace Dynamixel using protocol 2.0 or change function sync_read to readRegister.

**Comment by orasman** [comment]
i got it! thank you!
if you have plan to update your package to support v1.0 protocol, then i will wait.
if not, i have to do it bu myself.
but if i have trouble with that, i will ask to help again!
thanks a lot!

**Comment by routiful** [comment]
I will update it as soon as possible.

Thank you for your interest :)

**Comment by MarcoDotIO** [comment]
> Oh, you have used protocol 1.0.
> Protocol 1.0 doesn't support **sync_read**.
> If you want to read present_position of Dynamixel, displace Dynamixel using protocol 2.0 or change function sync_read to readRegister.

Hello there routiful,

I would like some clarification with this issue.

In my case, I daisychained two MX-106 motors (ID 2 and 3) for the arms, with another one (ID 1) controlling the head of a project I'm working on. This error only happens with motor IDs 2 and 3 and works completely fine with motor ID 1.

I would like you to clarify on the regard of "displace Dynamixel using protocol 2.0" regarding what change I need for my code.

And currently, the changes I have with the workbench operator are heavy, though I haven't touched any source code for the controller. I have linked the motor ID configuration files, along with the modified workbench joint operator code, in this comment.

[yaml_and_cpp_files.zip](https://github.com/ROBOTIS-GIT/open_manipulator/files/4223188/yaml_and_cpp_files.zip)

Please respond ASAP if there are any questions / concerns / issues here.
