### ISSUE TITLE
How to test open manipulator with 2 dynamixel

### ISSUE THREAD

**Issue by mohamad-75** [ROBOTIS-GIT/open_manipulator#92]
Hi guys!
I have two dynamixel XH430-V350R , How to test open manipulator with 2 dynamixel ?
please help me , thanks.

**Comment by gpwhd07** [comment]
Hi @mohamad-75 

I do not know the details of your situation.

OpenManipulator is a product that ROBOTIS sells.
If you want to make new manipulator with two dynamixel XH430-V350R that is not the OpenManipulator product, you need to modify a lot of our source code.
About the modification, please refer similar issue #84 .

**Comment by gpwhd07** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
