### ISSUE TITLE
Are there any inverse kinematics equations for the OpenManipulator Link?

### ISSUE THREAD

**Issue by changhongkuo** [ROBOTIS-GIT/open_manipulator#96]
I am currently working on the OpenManipulator Link and I saw this youtube video here:https://www.youtube.com/watch?v=WR9_1AheOok

I was wondering if you have the inverse kinematic equations for this particular robotic arm? I tried to use these equations from the robotis website (http://emanual.robotis.com/docs/en/software/rplus1/motion/#inverse-kinematics) but I did not get the correct results for the joint angles since the OpenManipulator Link model has a different design.
![image](https://user-images.githubusercontent.com/46854972/55036901-4247a580-4fd9-11e9-8f5c-c637b3446b1f.png)

Thank you very much for your help

**Comment by gpwhd07** [comment]
Hi @changhongkuo 

OpenManipulator Link has parallel linkage structure.
The website you referred explain simple serial linkage structure having 2DOF.

You can use many methods to solve Inverse kinematics for the parallel linkage structure. 
We used a geometrical method, you can refer it's source codes to [here 
](https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/OpenManipulator/example/Link/open_manipulator_link/link_kinematics.h)

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
